'%test':
  quarkus:
    datasource:
      db-kind: postgresql
      username: ${DB_USER:postgres}
      password: ${DB_PASS:postgres}
      jdbc:
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:aggro}_storage_benchmark
    hibernate-orm:
      database:
        generation: none
    flyway:
      migrate-at-start: true
      clean-at-start: true
