name: Java CI with Maven

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-18.04

    services:
      postgres:
        image: timescale/timescaledb:1.6.1-pg11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: aggro_test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Cache Maven dependencies
        id: cache-m2
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Produce Coverage reports
        run: mvn -B verify
        env:
          DB_HOST: postgres

      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
